######################################################################
# Automatically generated by qmake (2.01a) Fri May 31 11:56:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
OBJECTS_DIR = obj
DESTDIR = bin
# Input
HEADERS += src/TableRoom.h src/TwoPersonTable.h
SOURCES += src/main.cpp src/TableRoom.cpp src/TwoPersonTable.cpp
