######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 2 03:09:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
OBJECTS_DIR = obj
DESTDIR = bin
MOC_DIR = obj
# Input
HEADERS += src/Gobang.h
SOURCES += src/Gobang.cpp src/main.cpp
