######################################################################
# Automatically generated by qmake (2.01a) Thu May 30 10:09:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
OBJECTS_DIR = obj
DESTDIR = bin
# Input
SOURCES += src/main.cpp \
           src/Gobang.cpp
